name: Portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.6+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5
  change_app_package_name: ^1.5.0
  url_launcher: ^6.3.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#0A0E27"
  image: assets/images/splash.png
  fullscreen: true
  android: true
  ios: true
  web: false
  android_12:
    color: "#0A0E27"
    image: assets/images/profile_icon.png
    icon_background_color: "#0A0E27"
    fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_foreground_inset: 2